if(${PROJECT_NAME}_ENABLE_DOXYGEN)
    set(DOXYGEN_CALLER_GRAPH YES)
    set(DOXYGEN_PROJECT_NAME "NMBUFlowTorch")
    set(DOXYGEN_PROJECT_BRIEF "Creating a C++ interface for doing DNN related work")
    set(DOXYGEN_GENERATE_TREEVIEW YES)
    set(DOXYGEN_DISABLE_INDEX NO)
    set(DOXYGEN_FULL_SIDEBAR NO)
    set(DOXYGEN_HTML_EXTRA_STYLESHEET  .doxygen_style/doxygen-awesome.css)
    set(DOXYGEN_HTML_HEADER  .doxygen_style/header.html)
    set(DOXYGEN_PROJECT_LOGO .misc/NMBUFlowTorch.LOGO.thin.png)
    set(DOXYGEN_USE_MDFILE_AS_MAINPAGE = ./README.md)
    set(DOXYGEN_CALL_GRAPH YES)
    set(DOXYGEN_EXTRACT_ALL YES)
    set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/docs)

    find_package(Doxygen REQUIRED)
    find_package(Doxygen OPTIONAL_COMPONENTS dot)
    doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR})

    verbose_message("Doxygen has been setup and documentation is now available.")
endif()
